version: "3.9"  # optional since v1.27.0
services:
  server:
    build: server
    ports:
      - "5000:5000"
    networks:
      - main
  client:
    build: client_ng
    ports:
      - "3000:3000"
    networks:
      - main
  #nginx:
  #  build: nginx
  #  ports:
  #    - "80:80"
  #  networks:
  #    - main

networks:
  main: