version: "3.9" # optional since v1.27.0
services:
  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    depends_on:
      - server
      - client
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  client:
    image: deltachess-client
    container_name: deltachess-client
    build:
      context: ./client_ng
    depends_on:
      - server
    ports:
      - 3000:3000
    restart: on-failure

  server:
    image: deltachess-server
    container_name: deltachess-server
    build:
      context: ./server
    ports:
      - 5000:5000
    restart: on-failure
