[package]
name = "chess"
version = "0.1.0"
authors = ["ananas-dev <lucienfiorini@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2"
