[package]
name = "deltachess-backend"
version = "0.1.0"
authors = ["ananas-dev <lucienfiorini@protonmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-cors = "0.5"
env_logger = "0.8"
serde = "1.0.103"
serde_json = "1.0.44"
serde_derive = "1.0.103"
juniper = "0.14.0"
